spring:
  datasource:
    driver-class-name: com.kingbase.Driver
    url: jdbc:kingbase://127.0.0.1:54321/u_01_tkyw
    username: SYSTEM
    password: dc01

server:
    port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dc.kingbasedemo.entity


